"""add difficulty to questions and image_url to options

Revision ID: 1d937af3b7b8
Revises: 4e04b3ba62f0
Create Date: 2026-03-26 13:53:03.679403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d937af3b7b8"
down_revision: Union[str, Sequence[str], None] = "4e04b3ba62f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("questions", sa.Column("difficulty", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "difficulty")
    # ### end Alembic commands ###
