"""Add teams to sessions

Revision ID: 2d72960bbb32
Revises: 94eda39abef2
Create Date: 2026-03-27 12:56:31.766655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d72960bbb32"
down_revision: Union[str, Sequence[str], None] = "94eda39abef2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING", "ACTIVE", "COMPLETED", name="teamstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_teams_session_id"),
        "session_teams",
        ["session_id"],
        unique=False,
    )
    op.add_column("session_players", sa.Column("team_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_session_players_team_id"), "session_players", ["team_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "session_players",
        "session_teams",
        ["team_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("session_progress", sa.Column("team_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_session_progress_team_id"),
        "session_progress",
        ["team_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "session_progress",
        "session_teams",
        ["team_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session_progress", type_="foreignkey")
    op.drop_index(op.f("ix_session_progress_team_id"), table_name="session_progress")
    op.drop_column("session_progress", "team_id")
    op.drop_constraint(None, "session_players", type_="foreignkey")
    op.drop_index(op.f("ix_session_players_team_id"), table_name="session_players")
    op.drop_column("session_players", "team_id")
    op.drop_index(op.f("ix_session_teams_session_id"), table_name="session_teams")
    op.drop_table("session_teams")
    # ### end Alembic commands ###
