"""add gameplay tables

Revision ID: 4e04b3ba62f0
Revises: d7e8f9a0b1c2
Create Date: 2026-03-24 23:48:54.235312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e04b3ba62f0"
down_revision: Union[str, Sequence[str], None] = "d7e8f9a0b1c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quest_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("session_code", sa.String(length=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "ACTIVE",
                "COMPLETED",
                "STOPPED",
                "SCHEDULED",
                name="sessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_sessions_quest_id"), "game_sessions", ["quest_id"], unique=False
    )
    op.create_index(
        op.f("ix_game_sessions_session_code"),
        "game_sessions",
        ["session_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_game_sessions_teacher_id"),
        "game_sessions",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "session_players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("guest_name", sa.String(length=255), nullable=True),
        sa.Column("guest_token", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_color", sa.String(length=7), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING", "PLAYING", "FINISHED", name="playerstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("results_available_until", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_players_guest_token"),
        "session_players",
        ["guest_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_session_players_session_id"),
        "session_players",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_players_user_id"), "session_players", ["user_id"], unique=False
    )
    op.create_table(
        "session_chat",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["session_players.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_chat_player_id"), "session_chat", ["player_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_chat_session_id"), "session_chat", ["session_id"], unique=False
    )
    op.create_table(
        "session_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("map_object_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ASSIGNED",
                "VIEWED",
                "ANSWERED",
                name="progressstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["map_object_id"], ["map_objects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["session_players.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["game_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_progress_player_id"),
        "session_progress",
        ["player_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_progress_resource_id"),
        "session_progress",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_progress_session_id"),
        "session_progress",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_progress_session_id"), table_name="session_progress")
    op.drop_index(
        op.f("ix_session_progress_resource_id"), table_name="session_progress"
    )
    op.drop_index(op.f("ix_session_progress_player_id"), table_name="session_progress")
    op.drop_table("session_progress")
    op.drop_index(op.f("ix_session_chat_session_id"), table_name="session_chat")
    op.drop_index(op.f("ix_session_chat_player_id"), table_name="session_chat")
    op.drop_table("session_chat")
    op.drop_index(op.f("ix_session_players_user_id"), table_name="session_players")
    op.drop_index(op.f("ix_session_players_session_id"), table_name="session_players")
    op.drop_index(op.f("ix_session_players_guest_token"), table_name="session_players")
    op.drop_table("session_players")
    op.drop_index(op.f("ix_game_sessions_teacher_id"), table_name="game_sessions")
    op.drop_index(op.f("ix_game_sessions_session_code"), table_name="game_sessions")
    op.drop_index(op.f("ix_game_sessions_quest_id"), table_name="game_sessions")
    op.drop_table("game_sessions")
    # ### end Alembic commands ###
