"""add team_id to run_chats

Revision ID: 65dfe39b94ad
Revises: 4f98f87402ed
Create Date: 2026-04-26 15:04:32.459323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65dfe39b94ad"
down_revision: Union[str, Sequence[str], None] = "4f98f87402ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_chats", sa.Column("team_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_run_chats_team_id"), "run_chats", ["team_id"], unique=False
    )
    op.create_foreign_key(
        None, "run_chats", "run_teams", ["team_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "run_chats", type_="foreignkey")
    op.drop_index(op.f("ix_run_chats_team_id"), table_name="run_chats")
    op.drop_column("run_chats", "team_id")
    # ### end Alembic commands ###
