"""Аllow solo in team to quests

Revision ID: 8edaaed88353
Revises: 1d937af3b7b8
Create Date: 2026-03-27 08:50:46.742103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8edaaed88353"
down_revision: Union[str, Sequence[str], None] = "1d937af3b7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quests",
        sa.Column(
            "allow_solo_in_team", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quests", "allow_solo_in_team")
    # ### end Alembic commands ###
