"""Moving some quest settings to session settings

Revision ID: 94eda39abef2
Revises: 8edaaed88353
Create Date: 2026-03-27 11:13:45.572143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94eda39abef2"
down_revision: Union[str, Sequence[str], None] = "8edaaed88353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game_sessions",
        sa.Column(
            "allow_solo_in_team",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "show_feedback_after_answer",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "show_score_after",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "show_correct_answers",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "keep_completed_in_materials",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "game_sessions",
        sa.Column(
            "allow_change_answers",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.drop_column("quest_settings", "show_score_after")
    op.drop_column("quest_settings", "distribute_texts_in_team")
    op.drop_column("quest_settings", "show_correct_answers")
    op.drop_column("quest_settings", "show_all_texts")
    op.drop_column("quest_settings", "keep_completed_in_materials")
    op.drop_column("quests", "max_players")
    op.drop_column("quests", "allow_solo_in_team")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quests",
        sa.Column(
            "allow_solo_in_team",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "quests",
        sa.Column("max_players", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "quest_settings",
        sa.Column(
            "keep_completed_in_materials",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "quest_settings",
        sa.Column("show_all_texts", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "quest_settings",
        sa.Column(
            "show_correct_answers", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "quest_settings",
        sa.Column(
            "distribute_texts_in_team",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "quest_settings",
        sa.Column(
            "show_score_after", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("game_sessions", "allow_change_answers")
    op.drop_column("game_sessions", "keep_completed_in_materials")
    op.drop_column("game_sessions", "show_correct_answers")
    op.drop_column("game_sessions", "show_score_after")
    op.drop_column("game_sessions", "show_feedback_after_answer")
    op.drop_column("game_sessions", "allow_solo_in_team")
    # ### end Alembic commands ###
