"""add preferred_language to user

Revision ID: ba8f4698e269
Revises: b5938c4dc845
Create Date: 2026-03-19 17:02:26.756017

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba8f4698e269"
down_revision: Union[str, Sequence[str], None] = "b5938c4dc845"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create PostgreSQL ENUM type manually
    userlanguage = sa.Enum("UK", "EN", name="userlanguage")
    userlanguage.create(op.get_bind(), checkfirst=True)

    # Add column with server_default to populate existing rows, preventing NotNullViolation
    op.add_column(
        "users",
        sa.Column(
            "preferred_language", userlanguage, nullable=False, server_default="UK"
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop column first
    op.drop_column("users", "preferred_language")

    # Drop PostgreSQL ENUM type manually
    userlanguage = sa.Enum("UK", "EN", name="userlanguage")
    userlanguage.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
