"""Maps and quests structure

Revision ID: f5dcb9e585dc
Revises: 7ac7474b1976
Create Date: 2026-03-23 22:11:56.198344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5dcb9e585dc"
down_revision: Union[str, Sequence[str], None] = "7ac7474b1976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("original_width", sa.Integer(), nullable=False),
        sa.Column("original_height", sa.Integer(), nullable=False),
        sa.Column("landscape_only_mobile", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "map_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("map_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("z_index", sa.Integer(), nullable=False),
        sa.Column("is_interactive", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_map_objects_map_id"), "map_objects", ["map_id"], unique=False
    )
    op.create_index(
        op.f("ix_map_objects_order_index"), "map_objects", ["order_index"], unique=False
    )
    op.create_index(op.f("ix_map_objects_slug"), "map_objects", ["slug"], unique=False)
    op.create_table(
        "map_translations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("map_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_map_translations_language"),
        "map_translations",
        ["language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_map_translations_map_id"), "map_translations", ["map_id"], unique=False
    )
    op.create_table(
        "quests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("map_id", sa.Uuid(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "ARCHIVED", name="queststatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("max_players", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_quests_map_id"), "quests", ["map_id"], unique=False)
    op.create_index(
        op.f("ix_quests_teacher_id"), "quests", ["teacher_id"], unique=False
    )
    op.create_table(
        "map_object_hints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("hint_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["map_objects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_map_object_hints_language"),
        "map_object_hints",
        ["language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_map_object_hints_object_id"),
        "map_object_hints",
        ["object_id"],
        unique=False,
    )
    op.create_table(
        "quest_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quest_id", sa.Uuid(), nullable=False),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column("random_order", sa.Boolean(), nullable=False),
        sa.Column("show_all_texts", sa.Boolean(), nullable=False),
        sa.Column("keep_completed_in_materials", sa.Boolean(), nullable=False),
        sa.Column("show_score_after", sa.Boolean(), nullable=False),
        sa.Column("show_correct_answers", sa.Boolean(), nullable=False),
        sa.Column("distribute_texts_in_team", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("quest_id"),
    )
    op.create_table(
        "quest_translations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quest_id", sa.Uuid(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "quest_id", "language", name="uq_quest_translations_quest_language"
        ),
    )
    op.create_index(
        op.f("ix_quest_translations_quest_id"),
        "quest_translations",
        ["quest_id"],
        unique=False,
    )
    op.create_table(
        "quest_resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quest_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resource_id"], ["resources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quest_resources_quest_id"),
        "quest_resources",
        ["quest_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quest_resources_quest_id"), table_name="quest_resources")
    op.drop_table("quest_resources")
    op.drop_index(
        op.f("ix_quest_translations_quest_id"), table_name="quest_translations"
    )
    op.drop_table("quest_translations")
    op.drop_table("quest_settings")
    op.drop_index(op.f("ix_map_object_hints_object_id"), table_name="map_object_hints")
    op.drop_index(op.f("ix_map_object_hints_language"), table_name="map_object_hints")
    op.drop_table("map_object_hints")
    op.drop_index(op.f("ix_quests_teacher_id"), table_name="quests")
    op.drop_index(op.f("ix_quests_map_id"), table_name="quests")
    op.drop_table("quests")
    op.drop_index(op.f("ix_map_translations_map_id"), table_name="map_translations")
    op.drop_index(op.f("ix_map_translations_language"), table_name="map_translations")
    op.drop_table("map_translations")
    op.drop_index(op.f("ix_map_objects_slug"), table_name="map_objects")
    op.drop_index(op.f("ix_map_objects_order_index"), table_name="map_objects")
    op.drop_index(op.f("ix_map_objects_map_id"), table_name="map_objects")
    op.drop_table("map_objects")
    op.drop_table("maps")
    # ### end Alembic commands ###
